/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ahastudio.http.server;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.CharBuffer;
import java.util.HashMap;
import java.util.Map;

public class App {
    public static Long newId = 0L;

    public static void main(String[] args) throws IOException {
        App app = new App();
        app.run();

    }

    private void run() throws IOException {

        Map<Long, String> tasks = new HashMap<>();

        // 1. Listen
        // 특정 port와 통신할 수 있는 serverSocket 객체 생성
        ServerSocket listener = new ServerSocket(8080, 0);
        System.out.println("Listening on port 8080...");

        while (true) {
            // 2. Accept
            /* 클라이언트가 서버에 연결을 요청하면
             * 서버 소켓이 accept 메서드를 호출하여 새로운 Socket을 return, 연결 수락함
             */
            Socket socket = listener.accept();
            System.out.println("Accept!");

            // 3. Request 읽기
            // 서버는 요청을 하는 것이 아니라 받는 것이기 때문에 읽기를 먼저해야 한다.
            String request = getRequest(socket);
            System.out.println("Request: " + request);

            // 4. Response
            String message = process(tasks, request);
            writeMessage(socket, message);

        }
    }

    private static String getRequest(Socket socket) throws IOException {

        Reader reader = new InputStreamReader(socket.getInputStream());

        CharBuffer charBuffer = CharBuffer.allocate(1_000_000);
        reader.read(charBuffer);

        charBuffer.flip();

        return charBuffer.toString();
    }

    private String getRequestMethod(String request) {
        // 요청 Method 가져오고자 request String을 자를 범위(0부터 HTTP까지) 선정하여 return
        // 예시 : GET /home.html HTTP
        return request.substring(0, request.indexOf("HTTP"));
    }

    private String process(Map<Long, String> tasks, String request) {
        String method = getRequestMethod(request);

        if (method.startsWith("GET /tasks")) {
            return processGetTask(tasks);
        }

        if (method.startsWith("POST /tasks")) {
            return processPostTask(tasks, request);
        }

        if (method.startsWith("PATCH /tasks/")) {
            return processPatchTask(tasks, request, method);
        }

        if (method.startsWith("DELETE /tasks/")) {
            return processDeleteTask(tasks, method);
        }

        return generateMessage("", "400 Bad Request");
    }

    private String processGetTask(Map<Long, String> tasks) {
        // java 객체를 json으로 만들어 String 변환
        String content = new Gson().toJson(tasks);

        return generateMessage(content, "200 OK");
    }

    private String processPostTask(Map<Long, String> tasks, String request) {
        String task = parsePayload(request, "task");

        if (task.equals("")) {
            return generateMessage("", "400 Bad Request");
        }

        tasks.put(generateTaskId(), task);
        String content = new Gson().toJson(tasks);

        return generateMessage(content, "201 Created");
    }

    private Long generateTaskId() {
        newId += 1;
        return newId;
    }

    private String parsePayload(String request, String value) {
        String[] lines = request.split("\n");
        // 요청의 마지막 줄에 json 형식의 본문이 있으므로 추출
        String lastLine = lines[lines.length - 1];

        // parsing 시도
        try {
            // 요청 마지막 줄을 JsonElement 객체로 변환
            JsonElement jsonElement = JsonParser.parseString(lastLine);
            // 변환된 JsonElement를 JsonObject로 변환
            JsonObject jsonObject = jsonElement.getAsJsonObject();
            // 요청된 value 이름에 해당하는 json 속성 값을 문자열로 추출하여 반환
            return jsonObject.get(value).getAsString();
        } catch (Exception e) {
            // 파싱 과정에서 오류 발생 시 빈 문자열 반환하는 예외처리
            return "";
        }
    }

    private String processPatchTask(Map<Long, String> tasks, String request, String method) {
        Long id = parseTaskId(method);

        if (tasks.containsKey(id) == false) {
            return generateMessage("", "404 Not Found");
        }

        String task = parsePayload(request, "task");

        if (task.equals("")) {
            return generateMessage("", "400 Bad Request");
        }

        tasks.put(id, task);
        String content = new Gson().toJson(tasks);

        return generateMessage(content, "200 OK");
    }

    private String processDeleteTask(Map<Long, String> tasks, String method) {
        Long id = parseTaskId(method);

        if (tasks.containsKey(id) == false) {
            return generateMessage("", "404 Not Found");
        }

        tasks.remove(id);
        String content = new Gson().toJson(tasks);

        return generateMessage(content, "200 OK");
    }

    private String generateMessage(String body, String statusCode) {
        byte[] bytes = body.getBytes();
        return "" +
                "HTTP/1.1 " + statusCode + "\n" +
                "Host: localhost:8080\n" +
                "Content-Length: " + bytes.length + "\n" +
                "Content-Type: application/json; charset=UTF-8\n" +
                "\n" +
                body;
    }

    private Long parseTaskId(String method) {
        String[] parts = method.split("/");

        return Long.parseLong((parts[2].trim()));

    }

    private static void writeMessage(Socket socket, String response) throws IOException {
        Writer writer = new OutputStreamWriter(socket.getOutputStream());
        writer.write(response);
        writer.flush();
    }
}
